//
// Created by steve on 18-4-29.
//

#ifndef COMPLEXITYPOSITIONING_HARDCONSTRAINTIMU_H
#define COMPLEXITYPOSITIONING_HARDCONSTRAINTIMU_H

class HardConstraintIMU {


};


#endif //COMPLEXITYPOSITIONING_HARDCONSTRAINTIMU_H
